DEVIATION = 'DEVIATION'
HEADACHE = 'headache'
VIOLATION = 'VIOLATION'
TUBERCULOSIS = 'TB'
VISUAL_LOSS = 'visual_loss'
WORKING = 'working'
MEDICATION_NONCOMPLIANCE = 'medication_noncompliance'
UNPERFOMED = 'Not yet Performed'
